kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: instrument-craft-shop
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: instrument-craft-shop
        version: v1
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: instrument-craft-shop
        image: docker.sebastian-daschner.com/instrument-craft-shop:1
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - curl -f localhost:9080/
          initialDelaySeconds: 30
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - curl -f localhost:9080/instrument-craft-shop/resources/health
          initialDelaySeconds: 40
      imagePullSecrets:
      - name: regsecret
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: instrument-craft-shop
  labels:
    app: instrument-craft-shop
spec:
  selector:
    app: instrument-craft-shop
  ports:
    - port: 9080
      name: http
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: instrument-craft-shop
  annotations:
    kubernetes.io/ingress.class: istio
spec:
  rules:
  - http:
      paths:
      - path: /instrument-craft-shop/.*
        backend:
          serviceName: instrument-craft-shop
          servicePort: 9080
---
